In [1]:
import numpy as np

# Arithmatic Operations


In [2]:
var = np.array([1,2,3,4,5])
var_add = var + 3
print(var_add)

[4 5 6 7 8]


In [9]:
var = np.array([1,2,3,4,5])

var_add1 = np.add(var,3)
print(var_add1)

[4 5 6 7 8]


In [3]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([2,3,4,5,6])
var_add1 = var1 + var2
print(var_add1)

[ 3  5  7  9 11]


In [8]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([2,3,4,5,6])
var_add1 = np.add(var1,var2)
print(var_add1)

[ 3  5  7  9 11]


In [4]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([2,3,4,5,6])
var_sub1 = var2 - var1
print(var_sub1)

[1 1 1 1 1]


In [5]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([2,3,4,5,6])
var_mul1 = var2 * var1
print(var_mul1)

[ 2  6 12 20 30]


In [6]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([2,3,4,5,6])
var_div1 = var2 / var1
print(var_div1)

[2.         1.5        1.33333333 1.25       1.2       ]


In [7]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([2,3,4,5,6])
var_mod1 = var2 % var1
print(var_mod1)

[0 1 1 1 1]


In [10]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([2,3,4,5,6])
var_pow1 = var1 ** var2
print(var_pow1)

[    1     8    81  1024 15625]


In [11]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([2,3,4,5,6])
var_pow1 = np.power(var1,var2)
print(var_pow1)

[    1     8    81  1024 15625]


In [14]:
var1 = np.array([1,2,3,4,5])
var_reciprocal1 = 1/var1
print(var_reciprocal1)

[1.         0.5        0.33333333 0.25       0.2       ]


In [15]:
var1 = np.array([1,2,3,4,5])
var_reciprocal1 = np.reciprocal(np.float32(var1))
print(var_reciprocal1)

[1.         0.5        0.33333334 0.25       0.2       ]


# 2D Array

In [16]:
var21= np.array([[1,2,3],[1,2,3]])
var22= np.array([[1,2,3],[1,2,3]])
var_add = var21 +var22
print(var_add)

[[2 4 6]
 [2 4 6]]
