# Arithmatic Functions

In [12]:
import numpy as np
var = np.array([2,3,1,4,5,6,2])
print(var)
print("Min value is: ", np.min(var), np.argmin(var))  # Minimum Value in the array
print("Max value is: ", np.max(var), np.argmax(var))  # Maximum Value in the array  

print("Sqrt: ", np.sqrt(var))                        # Square root of each element

[2 3 1 4 5 6 2]
Min value is:  1 2
Max value is:  6 5
Sqrt:  [1.41421356 1.73205081 1.         2.         2.23606798 2.44948974
 1.41421356]


axis 0 for colum
axis 1 for row in  a matrix. 

I have the following code:

In [11]:
var1 = np.array([[2,3,1],[9,5,6]])
print("Maximum Value is: ",np.max(var1,axis=1)) # Maximum value row wise
print("Minimum value is: ",np.min(var1,axis=1)) # Minimum value row wise
print()
print("Maximum Value is: ",np.max(var1,axis=0)) # Maximum value col wise
print("Minimum value is: ",np.min(var1,axis=0)) # Minimum value col wise

Maximum Value is:  [3 9]
Minimum value is:  [1 5]

Maximum Value is:  [9 5 6]
Minimum value is:  [2 3 1]


In [14]:
var2 = np.array([1,2,3])
print(np.sin(var2)) #sine value of array
print(np.cos(var2)) #cosine value of array

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


# Cumulitive sum
1 2 3 4 
cumsum will be
1 3 6 10 

In [15]:
var2 = np.array([1,2,3,4])
print(np.cumsum(var2))

[ 1  3  6 10]
