In [1]:
import numpy as np

# rand()
the function used to generate random value between 0 to 1

In [7]:
var = np.random.rand(4)
print(var)

[0.23586571 0.12362682 0.42560679 0.37472884]


In [8]:
var1 = np.random.rand(2,5)
print(var1)

[[0.08952156 0.14049986 0.75631282 0.58740192 0.02700131]
 [0.99585341 0.29126662 0.54747402 0.32889895 0.79446882]]


# randn()
close to 0 . either negative or positive

In [9]:
var2= np.random.randn(5)
print(var2)

[-1.58261302 -1.3866063  -0.37520901  0.4830706  -0.56096788]


# randf()
generate random sampling in numpy. It returns an array of specified shape and fills it with random floar in the half open interval [0.0,1.0)

In [10]:
var3 = np.random.ranf(4)
print(var3)

[0.48471344 0.35429754 0.93900297 0.51067007]


# randint()
used to generate random number in a given range


In [14]:
var4 = np.random.randint(0,10)
print(var4) # only one value....

var5= np.random.randint(5,20,4) # generate 4 elements
print(var5)

8
[19 11 17 17]
