# Broadcasting


In [3]:
import numpy as np
var1= np.array([1,2,3,4])
print(var1.shape)
print(var1)
print()

var2 = np.array([[1],[2],[3]])
print(var2.shape)
print(var2)
print()

print(var1+var2)

(4,)
[1 2 3 4]

(3, 1)
[[1]
 [2]
 [3]]

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


1. Same Dimention
2. If dimention is different.. one of them must have 1
\n(1x3)  and (3x1) are different but has 1
so  it take maximum  from the first matrix which is 3, so the result will be 3x3

(1x3)  and (1x4) will output Broadcast Error

In [4]:
var3= np.array([[1],[2]]) # (2x1)
print(var3)
print(var3.shape)
print()

var4 = np.array([[1,2,3],[1,2,3]]) # (2x3)
print(var4)
print(var4.shape) 

print()
print(var3+var4) # broadcasting: (2x3)
print((var3+var4).shape)

[[1]
 [2]]
(2, 1)

[[1 2 3]
 [1 2 3]]
(2, 3)

[[2 3 4]
 [3 4 5]]
(2, 3)
