# Shuffle

In [3]:
import numpy as np
var = np.array([1,2,3,4,5,6])
print(var)
print()

np.random.shuffle(var)
print(var)

[1 2 3 4 5 6]

[4 5 1 3 6 2]


# Unique

In [6]:
import pprint


var1= np.array([1,2,4,2,3,4,5,6,5])
print(var1)
x= np.unique(var1,return_index=True, return_counts=True)
print(x)

[1 2 4 2 3 4 5 6 5]
(array([1, 2, 3, 4, 5, 6]), array([0, 1, 4, 2, 6, 7], dtype=int64), array([1, 2, 1, 2, 2, 1], dtype=int64))


# Resize

In [8]:
var2 = np.array([1,2,3,4,5,6])
y= np.resize(var2,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


# Flatten and Ravel

In [18]:
var2 = np.array([1,2,3,4,5,6])
y= np.resize(var2,(3,2))
print(y)
print()
print(y.flatten())
print()

print(y.flatten(order='F')) # column-major (fortran-style) order   

print("Ravel: " , np.ravel(y,order="K"))

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]

[1 3 5 2 4 6]
Ravel:  [1 2 3 4 5 6]
