# Insert

In [5]:
import numpy as np
var = np.array([1, 2, 3,4])
print(var)

v= np.insert(var,(0,3),9) # Insert at index 0 and 3 the value 9
print(v)

[1 2 3 4]
[9 1 2 3 9 4]


In [12]:
var2= np.array([[1,2,3],[1,2,3]])
v2= np.insert(var2,2,[6,4,4],axis=0) #Insert a row at the beginning of array  
print("Array after inserting a row:") 
print(v2)

Array after inserting a row:
[[1 2 3]
 [1 2 3]
 [6 4 4]]


# Append

In [26]:
x= np.append(var2,0) # can insert float
print(x)
v1= np.array([[1,2,3],[1,2,4]])
y = np.append(v1,[[0],[0]],axis=1)
print(y)

[1 2 3 1 2 3 0]
[[1 2 3 0]
 [1 2 4 0]]


# Delete

In [28]:
var1 = np.array([1,2,3,4])
print(var1)
d=np.delete(var1,1)
print(d)

[1 2 3 4]
[1 3 4]
