# Iterator

In [2]:
import numpy as np
x= np.array([4,5,6,7,8])
for i in x:
    print(i)

4
5
6
7
8


In [5]:
var1= np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()

for j in var1:
    print(j)

print()

for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [11]:
var3 = np.array([[[1,2,3,4],[5,6,7,7],[8,9,0,1]]])
print(var3)
print()

for i in var3:
    print(i)
print()

for j in var3:
    for k in j:
        for i in k:
            print(i)

[[[1 2 3 4]
  [5 6 7 7]
  [8 9 0 1]]]

[[1 2 3 4]
 [5 6 7 7]
 [8 9 0 1]]

1
2
3
4
5
6
7
7
8
9
0
1


In [14]:


var3 = np.array([[[1,2,3,4],[5,6,7,7],[8,9,0,1]]])
print(var3)
print()

for i in np.nditer(var3,flags=['buffered'],op_dtypes=['S']):
    print(i)

[[[1 2 3 4]
  [5 6 7 7]
  [8 9 0 1]]]

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'7'
b'8'
b'9'
b'0'
b'1'


In [15]:

var3 = np.array([[[1,2,3,4],[5,6,7,7],[8,9,0,1]]])
print(var3)
print()

for i,d in np.ndenumerate(var3):
    print(i,d)

[[[1 2 3 4]
  [5 6 7 7]
  [8 9 0 1]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 7
(0, 2, 0) 8
(0, 2, 1) 9
(0, 2, 2) 0
(0, 2, 3) 1
