# Matrix

In [4]:
import numpy as np
var = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
var = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(var)
print(type(var))
print()

var1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var1)
print(type(var1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


# Addition

In [7]:
var = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
var1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(var+var1)
print()
print(var-var1)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# Dot

In [8]:
print(var.dot(var1))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# Matrix Functions in Numpy Array
Transpose, Swapaxes, Inverse, Power, Determinate


In [14]:

var = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(var)
print()

print("Transpose of matrix: ")
print(np.transpose(var))
print()
print(var.T) # shortcut
print()




[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of matrix: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Swap Axis: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Swipe Axis

In [15]:
print(var)
print("Swap Axis: ")
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Swap Axis: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Inverse

In [17]:
var = np.matrix([[1,2],[3,4]])
print(var)
print("Inverse Matrix: ")
print(np.linalg.inv(var))

[[1 2]
 [3 4]]
Inverse Matrix: 
[[-2.   1. ]
 [ 1.5 -0.5]]


# Power
np.linalg.Matrix_power(var,n)

n> 0  power(mult)

n=0 [[1 0]


    [0 1]] identity matrix
    
n<0 Inveser * power

In [22]:
print(var)
print()

print(np.linalg.matrix_power(var,2))


[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]


# Determinant
np.linalg.det(var)

In [23]:
print(var)
print()
print("Determenent of matrix is: ")
print(np.linalg.det(var))

[[1 2]
 [3 4]]

Determenent of matrix is: 
-2.0000000000000004
