# Array

In [2]:
import numpy as np
x = [1,2,4,5]
print(x)

y= np.array([1,2,3,4])
print(type(y))

[1, 2, 4, 5]
<class 'numpy.ndarray'>


In [5]:
l =[]
for i in range(1,5):
    int_i = int(input("Enter: "))
    l.append(int_i)
print(np.array(l))

[1 2 3 4]


## MultiDImention array

In [11]:
ar2=np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

arr3d = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(arr3d)
print(arr3d.ndim)

arrMd=np.array([1,2,3,4],ndmin=10)
print(arrMd)
print(arrMd.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3
[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
