'''Array with 0

Array with 1

Empty Array

Range of element

Diagonal elements with 1

array with values that are spaced linearly in a specified interval'''

In [5]:
import numpy as np

# Zeros


In [7]:
ar_zero = np.zeros(4)
print(ar_zero)
print()
ar_zeros_1 = np.zeros((3,4))
print(ar_zeros_1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [8]:
ones = np.ones(4)
print(ones)
print()

ones_1 = np.ones((3,4))
print(ones_1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty

In [10]:
ar_empty = np.empty(4)
print(ar_empty)

[1. 1. 1. 1.]


# Range


In [11]:
ar_rn = np.arange(5) #like range function
print(ar_rn)

[0 1 2 3 4]


# Array Diagonal Element with 1

In [14]:
ar_Dia = np.eye(3) # makes 2d array diagonally to 1
print(ar_Dia)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Array with Special Interval
linspace

In [15]:
ar_lin = np.linspace(0,10,5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]
