# Shape

In [1]:
import numpy as np


In [3]:
var = np.array([[1,2],[1,2]])
print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [7]:
var1 = np.array([1,2,3], ndmin=3)
print(var1)
print(var1.ndim)
print()

print(var1.shape)

[[[1 2 3]]]
3

(1, 1, 3)


# Reshape


In [11]:
var2 = np.array([1,2,3,4,5,6])
x = var2.reshape(3,2)
print(x)


[[1 2]
 [3 4]
 [5 6]]


In [12]:
var3 = np.array([1,2,3,4,5,6,1,2,3,1,1,1])
x1 = var3.reshape(2,3,2)
print(x1)

print()



[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 1]
  [1 1]]]


In [13]:
one = x.reshape(-1)
print(one)

[1 2 3 4 5 6 1 2 3 1 1 1]
