# Indexing and Slicing

In [1]:
import numpy as np

# Indexing

In [3]:
var1 = np.array([1,2,3,4])
print(var1[1]) # 2
print(var1[-4]) # 1


2
1


In [6]:
var2 = np.array([[9,8,7],[4,5,6]])
print(var2)
print(var2.ndim)
print()

print(var2[0,1])

[[9 8 7]
 [4 5 6]]
2

8


In [10]:
var3 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(var3)
print(var3.ndim)
print()

print(var3[0,1,1])


[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
3

4


# Slicing

In [14]:
var = np.array([1,2,3,4,5,6,7,8,9])
print(var)
print()
print(var[0:5])  # prints the first 5 elements of array 'var'


[1 2 3 4 5 6 7 8 9]

[1 2 3 4 5]


In [16]:
#slicing with step size
print(var[0:5:2]) # start index 0, stop before index 6 (not included), step is 2. It will print [0, 2, 5 ]   

[1 3 5]


In [18]:
# slicing from n to end
print(var[2:])

[3 4 5 6 7 8 9]


In [19]:
#from start to n
print(var[:5])

[1 2 3 4 5]


In [20]:
# stop
print(var[::])

[1 2 3 4 5 6 7 8 9]


# 2D Slicing

In [25]:
var = np.array([[9,8,7,6],[11,12,13,14],[1,2,3,4]])
print(var[0,1:])  # prints [8  7  6]



print(var[:,0])    # prints [9 11 1]

[8 7 6]
[ 9 11  1]


# 3D Slicing


In [30]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(x)

#print only 7 8 9


SyntaxError: invalid syntax (4153658373.py, line 4)